PROJECT_NAME: ""
PROJECT_VERSION: ""

LLM_URL: "http://<<please-set-llm-url>>"
LLM_MODEL_NAME: "llm-model"
EMBEDDINGS_LLM_MODEL_NAME: "embedding-llm-model"

INPUT_REPORT_FILE_PATH: "/path/to/report.html"
KNOWN_FALSE_POSITIVE_FILE_PATH: "/path/to/known_false_positives_file"
OUTPUT_FILE_PATH: "/path/to/output_excel.xlsx"
HUMAN_VERIFIED_FILE_PATH: "<<unknown>>"
GIT_REPO_PATH: "/path/to/git/repo"
LIBCLANG_PATH: "/path/to/libclang"
CONFIG_H_PATH: ""
SERVICE_ACCOUNT_JSON_PATH: ""

USE_KNOWN_FALSE_POSITIVE_FILE: true
CALCULATE_METRICS: true
DOWNLOAD_GIT_REPO: false

SHOW_FINAL_JUDGE_CONTEXT: true
SIMILARITY_ERROR_THRESHOLD: 2

RUN_WITH_CRITIQUE: false
USE_CRITIQUE_AS_FINAL_RESULTS: false
CRITIQUE_LLM_URL: ""
CRITIQUE_LLM_MODEL_NAME: ""

CHUNK_SIZE: 500
CHUNK_OVERLAP: 0
CHUNK_SEPARATORS:
  - "\n\n"
  - "\n"
  - "."
  - ";"
  - ","
  - " "
  - ""
