apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: sast-ai-workflow-pipelinerun
spec:
  pipelineRef:
    name: sast-ai-workflow-pipeline
  params:
    - name: REPO_REMOTE_URL
      value: "source/code/url"
    - name: falsePositivesUrl
      value: "false/positives/url"
    - name: LLM_URL
      value: ""
    - name: LLM_MODEL_NAME
      value: "llm-model"
    - name: EMBEDDINGS_LLM_URL
      value: ""
    - name: EMBEDDINGS_LLM_MODEL_NAME
      value: "embedding-llm-model"
    - name: PROJECT_NAME
      value: "project-name"
    - name: PROJECT_VERSION
      value: "project-version"
    - name: INPUT_REPORT_FILE_PATH
      value: "input-report"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: sast-ai-workflow-pvc
    - name: gitlab-token-ws
      secret:
        secretName: gitlab-token-secret
        items:
          - key: gitlab_token
            path: gitlab_token
    - name: llm-api-key-ws
      secret:
        secretName: llm-api-key-secret 
        items:
          - key: api_key 
            path: api_key 
    - name: embeddings-api-key-ws 
      secret:
        secretName: embeddings-api-key-secret 
        items:
          - key: api_key 
            path: api_key 
    - name: google-sa-json-ws 
      secret:
        secretName: google-service-account-secret 
        items:
          - key: service_account.json 
            path: service_account.json
    - name: cache-workspace
      persistentVolumeClaim:
        claimName: sast-ai-cache-pvc
